### ISSUE TITLE
iPhone 5 & 5c support

### ISSUE THREAD

**Issue by tjaadvd** [ArmandGrillet/Adios#11]
Is it possible to make this project suitable for arm7 iPhones? I'm asking because https://github.com/krishkumar/BlockParty does run on my iPhone 5c even though it is not 64bit. However, this Adios seems to be more advanced.

**Comment by armandgrillet** [comment]
Adios has been tested on a lot of devices and it didn't work well on 32bit devices thus I've changed the `UIRequiredDeviceCapabilities` value in `Info.plist` so that it cannot be installed on a 32bit device. 

If you really want to run it on your iPhone 5c, change the values concerning the required device capabilities of the app and the two content-blockers to only ask for an `armv7` architecture. However it has been tested and it doesn't work well, this is because Adios works with a lot of rules (around 45000 per content-blocker compared to [320 for BlockParty](https://github.com/krishkumar/BlockParty/blob/master/RediffBlock/blockerList.json)) thus the compilation needs a 64bit processor or it would take too much time.

**Comment by tjaadvd** [comment]
Alright, thanks for clearing that up!

Verstuurd vanaf mijn iPhone
